### ISSUE TITLE
some problem in Running heuristic algorithms

### ISSUE THREAD

**Issue by zlh004** [Weafre/RL-DASH#1]
i try to run 'tcp-stream-bitrate'. after it runs, it reports an error like this:
![TIM截图20200621130322](https://user-images.githubusercontent.com/38122569/85217115-c7c62b00-b3bf-11ea-8c4a-fe4538745f52.jpg)
looking forward to your answers. 
thanks a lot

**Comment by zlh004** [comment]
I have commented out the sentence :
NS_ASSERT_MSG (clientPosLog.is_open(), "Couldn't open clientPosLog file");
And then the code works.
Am I doing the right thing?

**Comment by dattnguyenx** [comment]
Hi @zlh004 
if logging client position is not important in your simulation, I think it is fine.

**Comment by zlh004** [comment]
thank u @Weafre
